name: Build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/README.md"
      - "doc/**"
      - "bin/**"

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: |
          GOOS=darwin GOARCH=arm64 make build
          chmod +x wordle

      - name: Read Version
        id: read_version
        run: |
          VERSION=$(cat VERSION)
          echo "Version: $VERSION"
          echo "::set-output name=version::$VERSION"

      # - name: Get PR Commits
      #   id: get_pr_commits
      #   run: |
      #     PR_COMMITS=$(git log --merges --pretty=format:"* %s" HEAD..HEAD~1)
      #     echo "Release Notes:"
      #     echo "$PR_COMMITS"
      #     echo "::set-output name=release_notes::$PR_COMMITS"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.read_version.outputs.version }}
          # body: ${{ steps.get_pr_commits.outputs.release_notes }}
          files: wordle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
