name: Build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/README.md"
      - "**/.gitignore"
      - "doc/**"
      - "bin/**"

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: |
          GOOS=darwin GOARCH=arm64 make build
          chmod +x wordle

      - name: Read Version
        id: read_version
        run: |
          VERSION=$(go run ./cmd/wordle/main.go -version)
          echo "Version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.read_version.outputs.version }}
          name: Terminal Wordle ${{ steps.read_version.outputs.version }}
          generate_release_notes: true
          files: wordle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
