name: Test

on:
  pull_request:
    paths-ignore:
      - "**/README.md"
      - "**/.gitignore"
      - "doc/**"
      - "bin/**"

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Run tests
        run: make check
